### PR TITLE
bioformats: track develop

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
For 5.8, track bioformats develop branch.

Includes the tracking updates also in https://github.com/ome/bio-formats-build/pull/16.  Also see this PR for test instructions.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
@sbesson This is for the 5.8.x docs building on the other CI.  If you copy the east-ci jobs and switch the branch from `master` to `5.8`, this will get you the same setup as on east-ci, but building 5.8 including the documentation.

**Comment by sbesson** [comment]
See https://web-proxy.openmicroscopy.org/west-ci/job/BIOFORMATS-push-2/3/console. Does `scripts/repositories.yml` need to be adjusted accordingly (or could be generated from the tracking branch from `.gitmodules` if existing?)

**Comment by rleigh-codelibre** [comment]
Yes, I've pushed an update to the branch configuration.

**Comment by sbesson** [comment]
Thanks, https://github.com/snoopycrimecop/bioformats/commit/c547bb68f8b60738c0253bcde60073fdcb8580a2 now merges all the Bio-Formats develop PRs as expected.

How to prevent https://github.com/snoopycrimecop/bioformats/commit/4b41593cb53e08a5ccab27d74c5f1653dff9fddc i.e. keep the dependencies pinned at their current versions on the stable 5.8 branch?

**Comment by sbesson** [comment]
https://github.com/snoopycrimecop/bio-formats-build/tree/west_merge_trigger :+1:

**Pull request merged**
