### PR TITLE
Add matlab component

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Already exists as a submodule, enable in the pom.

Check builds are green.

### CODE REVIEW

**Comment by joshmoore** [comment]
Are the other changes here intended?

**Comment by rleigh-codelibre** [comment]
Hmm, no.  I'll remove the unintentional updates!

**Comment by rleigh-codelibre** [comment]
Fixed now.

**Comment by joshmoore** [comment]
Merging to integrate examples

**Pull request merged**
